### PR TITLE
Added a solution for Rainfall task

### PR DESCRIPTION
**Pull request by OksankaV**

### CODE REVIEW

**Comment by lhalam** [comment]
Conflicting files
src/main/java/org/academy/kata/implementation/OksankaV/SixImpl.java

**Comment by OksankaV** [comment]
Resolved conflict

**Comment by lhalam** [comment]
Conflicting files
src/main/java/org/academy/kata/implementation/OksankaV/SixImpl.java

**Comment by OksankaV** [comment]
done

**Pull request merged**
