### PR TITLE
[find numbers divisible by]: complete task

### PR DESCRIPTION
**Pull request by Oleghon**

### CODE REVIEW

**Comment by lhalam** [comment]
Conflicting files
src/main/java/org/academy/kata/implementation/Oleghon/EightImpl.java

**Comment by Oleghon** [comment]
> Conflicting files src/main/java/org/academy/kata/implementation/Oleghon/EightImpl.java

Conflict resolved

**Comment by lhalam** [comment]
Conflicting files
src/main/java/org/academy/kata/implementation/Oleghon/EightImpl.java

**Comment by Oleghon** [comment]
> Conflicting files src/main/java/org/academy/kata/implementation/Oleghon/EightImpl.java

Conflict resolved

**Pull request merged**
